# ============================================================
# CT-to-Panoramic-Xray Diffusion - Global Parameters
# ============================================================

# Dataset paths
CSV_PATH = "/media/rotem/7045cbc8-3ee4-485f-a6ea-18f7520d2704/Shani/Carotid_Plaque_data/CT_PX_dataset_diffusion/Facial_PX_dataset.csv"

# Split CSVs (generated by preprocess_augmented.py — split first, then augment only train)
TRAIN_CSV_PATH = "/media/rotem/7045cbc8-3ee4-485f-a6ea-18f7520d2704/Shani/Carotid_Plaque_data/CT_PX_dataset_diffusion/train_augmented.csv"
VAL_CSV_PATH = "/media/rotem/7045cbc8-3ee4-485f-a6ea-18f7520d2704/Shani/Carotid_Plaque_data/CT_PX_dataset_diffusion/val.csv"
TEST_CSV_PATH = "/media/rotem/7045cbc8-3ee4-485f-a6ea-18f7520d2704/Shani/Carotid_Plaque_data/CT_PX_dataset_diffusion/test.csv"

# Preprocessed directory names (relative to root_dir)
CT_PREPROCESSED_DIR = 'CT_preprocessed'
PX_PREPROCESSED_DIR = 'PX_preprocessed'
CT_PREPROCESSED_AUG_DIR = 'CT_preprocessed_aug'
PX_PREPROCESSED_AUG_DIR = 'PX_preprocessed_aug'

# CSV column names
CT_ACCESSION_COL = 'CT_accession_number'
XRAY_ACCESSION_COL = 'XRAY_Accession_number'

# Device
DEVICE = "cuda"

